// flow-typed signature: 03621a3f583f32ebbe26d529ddc929fd
// flow-typed version: <<STUB>>/babel-plugin-transform-inline-imports-commonjs_v^1.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-inline-imports-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-inline-imports-commonjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-inline-imports-commonjs/transform-inline-imports-commonjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-inline-imports-commonjs/transform-inline-imports-commonjs.js' {
  declare module.exports: $Exports<'babel-plugin-transform-inline-imports-commonjs/transform-inline-imports-commonjs'>;
}
