// flow-typed signature: c1d8654122c611e348847550d6688923
// flow-typed version: <<STUB>>/licensor_v^4.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'licensor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'licensor' {
  declare module.exports: any;
}
